### ISSUE TITLE
[Bug] Pasting into text entry does not work on iOS

### ISSUE THREAD

**Issue by ss-proc** [CommunityToolkit/Maui.Markup#111]
### Description

Hi, I'm a Maui / markup newbie and stumbled into this problem. In the settings, copy and pasting into Text entry field doesn't work.

### Stack Trace

None. UI bug

### Link to Reproduction Sample

https://github.com/CommunityToolkit/Maui.Markup/tree/main/samples

### Steps to Reproduce

1. Run the sample app
2. Go to settings
3. Copy paste a number into the text entry

### Expected Behavior

Pasted value should show-up

### Actual Behavior

Paste does not work. But works in other app like Messages. So it looks like copy > saves to device clipboard but paste doesn't work in the Maui app. But paste works in other iOS apps.

### Basic Information

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### Workaround
None that I know of

### Reproduction imagery

https://user-images.githubusercontent.com/104405893/189470801-93f2421d-2206-454c-a050-5de5d4ac8767.mp4

**Comment by bijington** [comment]
@ss-proc have you tried this functionality in a new .NET MAUI project? I would be surprised if there was anything this toolkit is doing to cause the issue.

**Comment by bijington** [comment]
> Hi @bijington @brminnick To re-create this issue in the maui repo https://github.com/dotnet/maui/issues?q=is%3Aissue+is%3Aopen do I need to create this with xaml or can I use maui.markup?

You don't need to use XAML however I would advise against using Markup. You can build the sample using just C#
