### ISSUE TITLE
[Proposal] Extension bindings for AppTheme and AppThemeColor

### ISSUE THREAD

**Issue by fredericoregateiro** [CommunityToolkit/Maui.Markup#117]
# Extension bindings for AppTheme and AppThemeColor

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/157

## Link to Discussion

[AppThemeBinding in Markup #627](https://github.com/CommunityToolkit/Maui/discussions/627)

## Summary
[summary]: #summary

Create binding extensions for `SetAppTheme` and `SetAppThemeColor`

## Motivation
[motivation]: #motivation

## Detailed Design
[design]: #detailed-design

## Usage Syntax
[usage]: #usage-syntax

```cs
new Button().AppThemeBinding(Button.TextColorProperty, Colors.Green, Colors.Orange)
```

### C# Usage

```cs
public static TBindable AppThemeBinding<TBindable, T>(this TBindable bindable, BindableProperty bindableProperty, T light, T dark) where TBindable : BindableObject
{
    bindable.SetAppTheme(bindableProperty, light, dark);

    return bindable;
}
public static TBindable AppThemeColorBinding<TBindable>(this TBindable bindable, BindableProperty bindableProperty, Color light, Color dark) where TBindable : BindableObject
{
    bindable.SetAppThemeColor(bindableProperty, light, dark);

    return bindable;
}
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

## Unresolved Questions
[unresolved]: #unresolved-questions

**Comment by brminnick** [comment]
Thanks @fredericoregateiro! 

@bijington has volunteered to Champion this PR. The next step before we can review/merge a PR is to vote on this Proposal. 

To learn more about our process for new features, you can read the “Submitting a New Feature” section here: https://github.com/CommunityToolkit/Maui.Markup#submitting-a-new-feature
