### ISSUE TITLE
[Proposal] Add methods for all VisualElement Properties

### ISSUE THREAD

**Issue by mrlacey** [CommunityToolkit/Maui.Markup#142]
# Add methods for all VisualElement Properties

* [x] Proposed
* [x] Prototype
* [x] Implementation: [PR raised](https://github.com/CommunityToolkit/Maui.Markup/pull/141)
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests: at least one for each new method following the conventions for other methods in the class
* [x] Sample: Some uses of new methods added to the Markup sample app
* [x] Documentation: [PR raised in docs repo](https://github.com/MicrosoftDocs/CommunityToolkit/pull/166)

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/140

## Summary
[summary]: #summary

As part of ensuring that Maui.Markup can provide a fluent interface for all standard controls, it will be a good starting point for having fluent methods for all properties of `VisualElement` as this is the base class to a lot of common controls.

## Motivation
[motivation]: #motivation

Fill in some common gaps in the fluent methods for defining a control instance.
Avoid needing to use the clunky method of combining an object initializer and chained fluent methods.

## Detailed Design
[design]: #detailed-design

Fill in the gaps of extension methods for setting the remaining properties of `VisualElement` that do not have them.

The properties are:

- AnchorX
- AnchorY
- Background
- BackgroundColor
- Clip
- FlowDirection
- Opacity
- InputTransparent
- IsEnabled
- IsVisible
- RotationX
- RotationY
- Rotation
- ScaleX
- ScaleY
- TranslationX
- TranslationY
- ZIndex

These should all be simple extension methods that wrap setting the property and then returning the element.

The implementations will be of the style:

```csharp
public static TVisualElement AnchorX<TVisualElement >(this TVisualElement element, double anchorX) where TVisualElement : VisualElement
{
	element.AnchorX = anchorX;
	return element;
}
```

In addition to simple methods for the above properties, I also think it would be useful to add the following helper methods:

A method `Anchor()` that takes two values that can be applied to `AnchorX` and `AnchorY` with a single call.
A method `Scale()` that takes two values that can be applied to `ScaleX` and `ScaleY` with a single call.

## Usage Syntax
[usage]: #usage-syntax

With this change, it will be possible to write

```cs
new Label().Text("hello").Opacity(0.5).BackgroundColor(Colors.Red);
```

rather than having to write 

```cs
new Label{ Opacity = 0.5, BackgroundColor = Colors.Red }.Text("hello")
```

## Drawbacks
[drawbacks]: #drawbacks

It makes the assembly slightly larger by adding methods where some of these might be rarely used. 
It feels an appropriate trade-off for completeness though.

## Alternatives
[alternatives]: #alternatives

No real alternatives other than not doing this.
It just makes it easier to provide a more consistent way of writing code when defining a UI in C#.

## Unresolved Questions
[unresolved]: #unresolved-questions

n/a

**Comment by bijington** [comment]
Given that all the work has been done I would be happy to vote ahead of the standup so it could even potentially be released by the next standup.

One topic we have discussed further is eventually having a source generator to build all of these extension methods, I wonder if it could even write the tests for us... I think given the effort has gone into this approach we should go with it and then accept that it might be undone later down the line with SGs

**Comment by mrlacey** [comment]
> One topic we have discussed further is eventually having a source generator to build all of these extension methods, I wonder if it could even write the tests for us... I think given the effort has gone into this approach we should go with it and then accept that it might be undone later down the line with SGs

Is the discussion on using source generators documented somewhere? I can't find anything and have questions. Especially as it could only ever be a partial solution.

**Comment by bijington** [comment]
@mrlacey no sorry this was started as a discussion internal to the team. Happy to open it up here though, the discussion only really started around whether it was possible, I full accept it wouldn't be a whole and complete solution taking your `Anchor` extension method as an example.

What questions do you have?

**Comment by brminnick** [comment]
Approved in December Standup: https://www.youtube.com/watch?v=tqQhW104UKI

**Comment by brminnick** [comment]
Thanks again, Matt! Just doing some cleanup now, realizing that I forgot to close this as completed 🤦‍♂️ 😆
