### ISSUE TITLE
[Bug] Upgraded to latest version and .Net7 and generated classes for TextAlignmentGenerator do not compile

### ISSUE THREAD

**Issue by OmiCron07** [CommunityToolkit/Maui.Markup#143]
The call is ambiguous between the following methods or properties: 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Editor.TextCenterHorizontal(Microsoft.Maui.Controls.Editor)' and 'CommunityToolkit.Maui.Markup.TextAlignmentExtensions_Editor.TextCenterHorizontal(Microsoft.Maui.Controls.Editor)'	(net7.0-windows10.0.19041.0)	[REDACTED]\CommunityToolkit.Maui.Markup.SourceGenerators\CommunityToolkit.Maui.Markup.SourceGenerators.TextAlignmentExtensionsGenerator\EditorTextAlignmentExtensions.g.cs	122	Active

**Comment by brminnick** [comment]
Hi @OmiCron07! 



Please edit your Issue and include the information required in the [New Issue template](https://github.com/CommunityToolkit/Maui.Markup/issues/new?assignees=&labels=bug%2C+unverified&template=bug_report_template.md&title=%5BBug%5D+). We cannot help you solve this bug without the information we ask for in the New Issue template.

<details>

<summary>Bug Template</summary>

```
<!--
Hello, and thanks for your interest in contributing to the .NET MAUI Markup Toolkit! 

Please describe the issue below, including detailed steps for reproduction. If we are unable to reproduce the bug we will be unable to fix the issue and may close this Issue.

-->

### Description

<!-- Please provide a detailed description of the issue -->

### Stack Trace

<!-- Please copy/paste the complete stack trace (if applicable) -->

### Link to Reproduction Sample

<!-- Please link to a GitHub Repo or GitHub Page -->

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

### Actual Behavior

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: <!-- All that apply -->
  - iOS:  <!-- The version of the iOS SDK you are compiling against, e.g. 11.1 -->
  - Android: <!-- The version of the Android SDK you are compiling against, e.g. 7.1 --> 
  - UWP:  <!-- The version of the UWP SDK you are compiling against, e.g. 16299 --> 
- Android Support Library Version: <!-- if applicable -->
- Nuget Packages:
- Affected Devices:

### Workaround
<!-- If you've found a way around this issue, help other users out and share the workaround -->

### Reproduction imagery

<!-- If it is a visual issue, please include imagery (GIF/Screenshots) showing the problem -->

```
</details>
