### ISSUE TITLE
[BUG] Build fails when including class library project including CommunityToolkit.Maui.Markup.

### ISSUE THREAD

**Issue by maximfrisk** [CommunityToolkit/Maui.Markup#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Build fails when referencing a class library project that includes the CommunityToolkit.Maui.Markup NuGet.

### Expected Behavior

Successful build with referencing a class library project that includes the CommunityToolkit.Maui.Markup NuGet.

### Steps To Reproduce

1. Open and run the project solution from the repository. 
2. When building the project referencing the class library project (where the Markup nuget is installed) observe the output log:

<img width="1879" alt="Screenshot 2022-11-30 at 16 31 11" src="https://user-images.githubusercontent.com/7091637/204843102-cd893257-89c9-4528-afc8-6e4c56e9373a.png">

### Link to public reproduction project repository

https://bitbucket.org/maximfrisk/markup/src/master/

### Environment

```markdown
- .NET MAUI C# Markup CommunityToolkit: 2.0.0
- OS: MacOS Ventura 13.0.1 (22A400)
- .NET MAUI: 7.0.49
- Visual Studio 17.5 Preview (17.5 build 437)
```

**Comment by brminnick** [comment]
Duplicate https://github.com/CommunityToolkit/Maui.Markup/issues/158

**Comment by brminnick** [comment]
Fixed in https://github.com/CommunityToolkit/Maui.Markup/pull/159

**Comment by maximfrisk** [comment]
Great news! sorry for duplicated repport :)
