### ISSUE TITLE
[Proposal] Further enhance typed binding support by adding BindCommand

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui.Markup#181]
### Feature name

Further enhance typed binding support by adding `BindCommand`

### Link to discussion

n/a

### Progress tracker

- [x] Android Implementation
- [x] iOS Implementation
- [x] MacCatalyst Implementation
- [x] Windows Implementation
- [x] Tizen Implementation
- [x] Unit Tests
- [x] Samples
- [x] Documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/226/files

### Summary

The work carried out in #155 didn't bring full typed binding support up to par with the existing binding support. We want to add in the `BindCommand` implementation to match the old binding functionality.

### Motivation

Quicker bindings means quicker apps.

### Detailed Design

```csharp
public static TBindable BindCommand<TBindable, TBindingContext, TSource>(
    this TBindable bindable,
    Func<TBindingContext, TSource> getter,
    TSource? source = null,
    string? parameterPath = Binding.SelfPath,
    object? parameterSource = null) where TBindable : BindableObject
{
    ...
}
```

### Usage Syntax

```markdown
new Button().BindCommand(static (ViewModel vm) => vm.SubmitCommand);
```

**Comment by egvijayanand** [comment]
Is it necessary to mark the expression method as static?

Does it bring any benefits as have seen in the Bind method as well?

@brminnick

**Comment by brminnick** [comment]
`static` is a recommended because it gives a performance boost to anonymous methods:  https://paulsebastian.codes/static-anonymous-functions-with-c-9-quick-overview

You don't have to use static anonymous methods, but it is recommended.

**Comment by brminnick** [comment]
I approve ✅

**Comment by bijington** [comment]
I approve ✅

**Comment by VladislavAntonyuk** [comment]
Approve
