### ISSUE TITLE
[Proposal] Absolute layout LayoutBounds and LayoutFlag extension

### ISSUE THREAD

**Issue by danielftz** [CommunityToolkit/Maui.Markup#25]
# Absolute layout LayoutBounds and LayoutFlag markup extension

* [x] Proposed
* [x] Prototype
* [X] Implementation
* [X] Unit Tests
* [X] Documentation
* [X] Sample

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/22

## Summary
[summary]: #summary

I propose a _ViewInAbsoluteLayoutExtensions_ static class, where _LayoutBounds_ and _LayoutFlag_ static methods (and their overloads) are implemented. 

In most cases when using _AbsoluteLayout,_ every child view will need to define two attached properties, _LayoutBounds_ and _LayoutFlag_, where _LayoutBounds_ is a _Rectangle_ struct and _LayoutFlag_ is an _AbsoluteLayoutFlags_ Enum. Thus, the _ViewInAbsoluteLayoutExtensions_ will offer the child View the ability to define these two attached properties declaratively. 

Example: 
```cs
BoxView box= new BoxView
{
   Color = Colors.Red,
}.LayoutBounds(0.5, 0.5, 100, 100)
.LayoutFlags(AbsoluteLayoutFlags.PositionProportional);
```

## Motivation
[motivation]: #motivation

Currently In MCT Markup, there are no declarative way to define _LayoutBounds_ and _LayoutFlag_ (like Row and Column for child Views in Grid) 

## Detailed Design
[design]: #detailed-design

The _ViewInAbsoluteLayoutEx tensions_ static class should at the very least include 4 extension methods to cover the 4 basic use cases,

-  setting _AbsoluteLayoutFlags_
```cs
public static TView LayoutFlags<TView>(this TView view, AbsoluteLayoutFlags flag) where TView : View
{
    view.SetValue(AbsoluteLayout.LayoutFlagsProperty, flag);
    return view;
}
```

- setting position only _LayoutBounds_ value (Not sure if this implementation is correct)
```cs
public static TView LayoutBounds<TView>(this TView view, Point point) where TView : View
{
    view.SetValue(AbsoluteLayout.LayoutBoundsProperty, point);
    return view;
}
```

- setting position and size _LayoutBounds_ value
```cs
public static TView LayoutBounds<TView>(this TView view, Rectangle rectangle) where TView : View
{
    view.SetValue(AbsoluteLayout.LayoutBoundsProperty, rectangle);
    return view;
}
```
Additionally, LayoutBounds method should have overloads mostly for the purpose of ease of use. Allowing the user to input in x,y,width,height directly, instead of encapsulating these values in a Rectangle struct. 

```cs
public static TView LayoutBounds<TView>(this TView view, int x, int y) where TView : View
public static TView LayoutBounds<TView,TCoord>(this TView view, TCoord x, TCoord y) where TView : View where TCoord : Enum
public static TView LayoutBounds<TView>(this TView view, int x, int y, int width , int height) where TView : View
public static TView LayoutBounds<TView, TCoord>(this TView view, TCoord x, TCoord y, TCoord width, TCoord height) where TView : View where TCoord : Enum
public static TView LayoutBounds<TView>(this TView view, Point point, Size size) where TView : View
```

There also needs to be a private _ToDouble_ helper method in this class, as double is expected input type for _Rectangle_ struct 
```
static double ToDouble(this Enum enumValue) => Convert.ToDouble(enumValue, CultureInfo.InvariantCulture);
```

## Drawbacks
[drawbacks]: #drawbacks

None that i can think of. 

## Alternatives
[alternatives]: #alternatives

None that i can think of. 

## Unresolved Questions
[unresolved]: #unresolved-questions

- For child View objects that need to use _AbsoluteValue.AutoSize_, the implementation still needs more testing. 
- Sometimes if the user only wants to change the position or the size of the child View, should they be given the option to do that with one of the overloads?

**Comment by brminnick** [comment]
Thanks @danielftz! I'll champion this proposal and add it to our next standup for a vote/approaval 🙌

**Comment by brminnick** [comment]
I approve this Proposal ✅

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by bijington** [comment]
I approve too

**Comment by brminnick** [comment]
Congrats @danielftz! This Proposal has officially been approved and can be implemented! 

Would you like to also do the implementation and open a Pull Request?
