### ISSUE TITLE
[BUG] Typed bindings is not working as expected.

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/Maui.Markup#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you read the "Reporting a bug" section on Contributing file?

- [X] I have read the "Reporting a bug" section on Contributing file: https://github.com/CommunityToolkit/Maui.Markup/blob/main/CONTRIBUTING.md#reporting-a-bug

### Current Behavior

Typed binding breaks the working behavior of the controls, whereas classic binding works in the way it is designed.

### Expected Behavior

Like how it works in classic binding, only the approach changes with improved type safety.

### Steps To Reproduce

1. Clone the repository
2. Run the sample app
3. It hosts two controls on the Main page of the app, both are pickers, one with typed binding and the other with classic binding
4. Both are bound to the same Index property, which means a change in one picker should reflect in the other
5. Now change the value in the type picker and no response in the classic picker (the issue)
6. Then change the value in the classic picker, there is a change in the type picker (actual behavior)

### Link to public reproduction project repository

https://github.com/egvijayanand/markup-issue-272

### Environment

```markdown
- .NET MAUI C# Markup CommunityToolkit: v4.0.0
- OS: Windows 11 v10.0.22631.2715
- .NET MAUI: v8.0.3
```

**Comment by egvijayanand** [comment]
Kindly wait for a few moments, will upload the sample app. Was waiting for the issue id.

**Comment by egvijayanand** [comment]
Here's the GitHub repository with sample [repo](https://github.com/egvijayanand/markup-issue-272)

Kindly let me know if I missed anything, as a last measure even tried using Two-way binding, but no change in the output.

It's not only to Picker as have tried with another sample that hosts a variety of controls, nothing is working after updating to Typed bindings.

**Comment by brminnick** [comment]
Hey Vijay! 

It looks like you've only implemented One-Way binding. You've bound the getter of `Picker.ItemsSourceProperty` to read `MainViewModel.Index`, but you haven't told the binding how to set the value when it changes.

You just need to add this as the setter for your Typed Binding:

```cs
static (MainViewModel vm, int index) => vm.Index = index
```

## One-Way Binding (Read-Only)

```cs
 new Picker().Bind(Picker.ItemsSourceProperty, static (MainViewModel vm) => vm.Numbers)
                                .Bind(Picker.SelectedIndexProperty, 
                                        static (MainViewModel vm) => vm.Index, 
                                        mode: BindingMode.TwoWay),
```

## Two-Way Binding (Read-Write)

```cs
 new Picker().Bind(Picker.ItemsSourceProperty, static (MainViewModel vm) => vm.Numbers)
                                .Bind(Picker.SelectedIndexProperty, 
                                        static (MainViewModel vm) => vm.Index, 
                                        static (MainViewModel vm, int index) => vm.Index = index,
                                        mode: BindingMode.TwoWay),
```

**Comment by brminnick** [comment]
I'd love your help updating our docs to make this more clear! 

Or point me to whatever resource where you were learning Typed Bindings and we'll see if we can update that 💯

**Comment by egvijayanand** [comment]
I understand @brminnick, may be an understanding gap. Thanks.

But definitely feel it's an overhead, as most of the time we work with two-way data-binding and it writes back to the same property from where the read happens.

Is there a way to automate things so that we need to write the explicit setter only if there's logic involved?

**Comment by brminnick** [comment]
> But definitely feel it's an overhead, as most of the time we work with two-way data-binding and it writes back to the same property from where the read happens.

Yup - this is the biggest difference between the previous way of declaring bindings and Typed Bindings.

> Is there a way to automate things so that we need to write the explicit setter only if there's logic involved?

It may be possible. It'd require a lot of forethought and unit testing to make sure we don't break any default behavior, though; I'm not sure if the `TypedBinding` class is meant to handle that scenario. 

If you want to try it out feel free to submit a [New Feature Proposal](https://github.com/CommunityToolkit/Maui.Markup/issues/new?assignees=&labels=new%2Cproposal&projects=&template=open-a-new-feature-proposal.yml&title=%5BProposal%5D+).

**Comment by egvijayanand** [comment]
> It may be possible. It'd require a lot of forethought and unit testing to make sure we don't break any default behavior, though; I'm not sure if the `TypedBinding` class is meant to handle that scenario.

Not fully sure, but seems possible. Let me try with a sample and get back on this.

**Comment by brminnick** [comment]
Awesome! Yea, we'll want to test the new implementation against one-way bindings, two-way bindings, one-way-to-source bindings and one-time bindings.

There's also a `DefaultBindingMode` for every `BindableObject`, so we'll want to test it against BindableObjects that each have a different  `DefaultBindingMode`.


https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/binding-mode?view=net-maui-8.0
> Every .NET Multi-platform App UI (.NET MAUI) bindable property has a default binding mode that is set when the bindable property is created, and which is available from the DefaultBindingMode property of the [BindableProperty](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.bindableproperty) object.

**Comment by egvijayanand** [comment]
> There's also a `DefaultBindingMode` for every `BindableObject`, so we'll want to test it against BindableObjects that each have a different `DefaultBindingMode`.

I'm a big fan of DefaultBinding (both property and mode). Last time when TypedBinding was in prototype, I asked for the possibility of having this in the context of typed too. Like Text property being the default for Label/Entry and so on and those are two-way too.

Let me check the implementation to validate the possibility.

**Comment by egvijayanand** [comment]
SelectedIndex is default and two-way, that's why I didn't check it in deep. Thought mapping itself is good enough to do a two-way binding and that's the reason tried to set the binding mode to two-way explicitly.

**Comment by egvijayanand** [comment]
Looks like, have cracked it.

I've [already tried this](https://github.com/CommunityToolkit/Maui.Markup/issues/155#issuecomment-1418211529). But just missed a single change while parsing the Func expression that made to hold that for so long.

Instead of adding a generic parameter, have assumed the return value of the Func expression as an object. Now have included that one.

This will work for default properties too :-)

Will add the extension methods to the same sample, publish a newer version, and will give an update.

**Comment by egvijayanand** [comment]
Have pushed the updated version. Have suffixed the Bind methods with **v2** as the parameter types clash with those from the package.

The method that parses the Property name from the LINQ expression definitely requires refactoring as it was written years ago.

@brminnick  Let me know your thoughts on this.

**Comment by brminnick** [comment]
No way! That was quick!!

Where can I find the code?

**Comment by egvijayanand** [comment]
Same repo. Just pull the latest version.

Regards,
Vijay Anand E G
________________________________

**Comment by egvijayanand** [comment]
Further discussion here - #343
