### ISSUE TITLE
[Proposal] Behaviors extension to VisualElementExtensions

### ISSUE THREAD

**Issue by bijington** [CommunityToolkit/Maui.Markup#29]
# Behaviors extension to VisualElementExtensions

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Link to Discussion

#28

## Summary
[summary]: #summary

I would like to propose that we add the `WithBehavior(this VisualElement visualElement, Behavior behavior)` and `WithBehaviors(this VisualElement visualElement, params Behavior[] behaviors)` extensions that will add the supplied `behavior` to `visualElement.Behaviors`.

## Motivation
[motivation]: #motivation

Reduces the amount of code developers need to write 😄 

## Detailed Design
[design]: #detailed-design

```csharp
public static class VisualElementExtensions
{
    public static WithBehavior(this VisualElement visualElement, Behavior behavior)
    {
        visualElement.Behaviors.Add(behavior);
        return visualElement;
    }

    public static WithBehaviors(this VisualElement visualElement, params Behavior[] behaviors)
    {
        foreach (var behavior in behaviors)
        {
            WithBehavior(behavior);
        }
        return visualElement;
    }
}
```

## Usage Syntax
[usage]: #usage-syntax

```csharp
Content = new Entry
{
    Placeholder = "Start typing until MaxLength is reached...",
    MaxLength = 100
}.WithBehavior(new MaxLengthReachedBehavior().Bind(
        MaxLengthReachedBehavior.CommandProperty,
        nameof(ViewModel.MaxLengthReachedCommand));
```

## Drawbacks
[drawbacks]: #drawbacks

n/a

## Alternatives
[alternatives]: #alternatives

n/a

## Unresolved Questions
[unresolved]: #unresolved-questions

n/a

**Comment by bijington** [comment]
Is `WithBehavior` the correct naming approach or should it just be `Behavior` to match other extensions?

**Comment by brminnick** [comment]
Good point! Looking at the existing extension methods like `DynamicResources` + `Effects`, I think we should create one extension method called `Behaviors`:

```cs
public static Behaviors(this VisualElement visualElement, params Behavior[] behaviors)
{
    foreach (var behavior in behaviors)
    {
        visualElement.Behaviors.Add(behavior);
    }
    return visualElement;
}
```

**Comment by bijington** [comment]
Hey team & community,

@brminnick @jfversluis @VladislavAntonyuk @pictos 

Would you mind voting on whether you would like to approve this PR or not. Given the RC is coming very soon it would be nice to get this in to help with the docs writing.

👍 for yes and 👎 for no

**Comment by bijington** [comment]
> I think this is done with merging the Docs?

Oh yeah thanks! Closed now 😄
