### ISSUE TITLE
[Proposal] Add `.Text()` and `.TextColor()` Extension Methods

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui.Markup#38]
# Add `.Text()` + `.TextColor()` Extension Methods

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/37

## Summary
[summary]: #summary

This Proposal adds extension methods for `IText.Text` and `ITextStyle.TextColor`.

## Motivation
[motivation]: #motivation

Currently, the only way to set `Text` and `TextColor` properties on an element that implements `IText` is to set the properties directly. Here is an example from `CommunityToolkit.Maui.Markup.Sample.Pages.SettingsPage`:

```cs
new Label { Text = "Top Stories To Fetch", TextColor = ColorConstants.PrimaryTextColor }
	.LayoutFlags(AbsoluteLayoutFlags.XProportional | AbsoluteLayoutFlags.WidthProportional)
	.LayoutBounds(0, 0, 1, 40)
	.TextCenterHorizontal()
	.TextBottom(),
```

This Proposal will allow devs to use fluent extension methods to set both `Text` and `TextColor`.

## Detailed Design
[design]: #detailed-design

```cs
	/// <summary>
	/// Sets <see cref="ITextStyle.TextColor"/> Property
	/// </summary>
	/// <typeparam name="TBindable"><see cref="BindableObject"/></typeparam>
	/// <param name="bindable">Element</param>
	/// <param name="textColor">Text <see cref="Color"/></param>
	/// <returns></returns>
	public static TBindable TextColor<TBindable>(this TBindable bindable, Color? textColor) where TBindable : BindableObject, ITextStyle
	{
		bindable.SetValue(TextElement.TextColorProperty, textColor);
		return bindable;
	}

	/// <summary>
	/// Sets <see cref="IText.Text"/> Property
	/// </summary>
	/// <typeparam name="TBindable"><see cref="BindableObject"/></typeparam>
	/// <param name="bindable">Element</param>
	/// <param name="text"></param>
	/// <returns></returns>
	public static TBindable Text<TBindable>(this TBindable bindable, string? text) where TBindable : BindableObject, IText
	{
		bindable.SetValue(ITextElement.TextProperty, text);
		return bindable;
	}

	/// <summary>
	/// Sets <see cref="IText.Text"/> Property
	/// </summary>
	/// <typeparam name="TBindable"><see cref="BindableObject"/></typeparam>
	/// <param name="bindable">Element</param>
	/// <param name="text"></param>
	/// <param name="textColor">Text <see cref="Color"/></param>
	public static TBindable Text<TBindable>(this TBindable bindable, string? text, Color? textColor) where TBindable : BindableObject, IText
	{
		return bindable.Text(text).TextColor(textColor);
	}
```

## Usage Syntax
[usage]: #usage-syntax

### C# Usage

```cs
Content = new VerticalStackLayout
{
  Children = 
  {
    new Label()
      .Text("Hello World", Colors.Blue),

    new Label()
      .TextColor(Colors.Green)
      .Bind(Label.TextProperty, nameof(ViewModel.LabelText);
  }
}

```

## Drawbacks
[drawbacks]: #drawbacks

Currently, [`TextElement` does not have a `TextProperty` static property](https://github.com/brminnick/maui/blob/main/src/Controls/src/Core/TextElement.cs), i.e. `TextElelement.TextProperty` does not yet exist.

We can workaround this by doing the following. This is a proven and common workaround in [Xamarin.CommunityToolkit.Markup](https://github.com/xamarin/XamarinCommunityToolkit/blob/f3663cd6d3f980b86b8cfc067123d81708db4abe/src/Markup/Xamarin.CommunityToolkit.Markup/ElementExtensions.cs#L3-L4).

```cs
using ITextElement = Microsoft.Maui.Controls.Label; // ToDo Remove this once TextElement.TextProperty is added

public static class ElementExtensions
{
	public static TBindable Text<TBindable>(this TBindable bindable, string? text) where TBindable : BindableObject, IText
	{
		bindable.SetValue(ITextElement.TextProperty, text);
		return bindable;
	}
}
```

## Alternatives
[alternatives]: #alternatives

Currently, the only alternative is to initialize the properties like so:
```cs
new Label { Text = "Top Stories To Fetch", TextColor = ColorConstants.PrimaryTextColor }
```

## Unresolved Questions
[unresolved]: #unresolved-questions

Should we support `null` inputs? The default value of `Color` and `Text` is `null` and I imagine the number of use cases where developer would use this `.Text()` to revert the values of `Color` and `Text` back to `null` may be minimal.

**Comment by bijington** [comment]
gets my vote!

**Comment by pictos** [comment]
I vote to approve it!

**Comment by brminnick** [comment]
I vote to approve ✅
