### ISSUE TITLE
[Proposal] Add `IPlaceholder` Extension Methods

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui.Markup#43]
# `IPlaceholder` Extension Methods

* [x] Proposed
* [x] Prototype
* [x] Implementation: Not Started
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/41

## Summary
[summary]: #summary

This Proposal adds the following extension methods to support `IPlaceholder` controls:

```cs
public static TBindable PlaceholderColor<TBindable>(this TBindable bindable, Color? textColor) where TBindable : BindableObject, IPlaceholder
public static TBindable Placeholder<TBindable>(this TBindable bindable, string? text) where TBindable : BindableObject, IPlaceholder
public static TBindable Placeholder<TBindable>(this TBindable bindable, string? text, Color? textColor) where TBindable : BindableObject, IPlaceholder
```

## Motivation
[motivation]: #motivation

We recently approved the implementation of `.Text()` in #38 for `IText` and `ITextStyle` controls. 

This proposal is the next logical step to also implement the extension methods `.Placeholder()` and `.PlaceholderColor()`.

## Detailed Design
[design]: #detailed-design

```cs
public static TBindable PlaceholderColor<TBindable>(this TBindable bindable, Color? textColor) where TBindable : BindableObject, IPlaceholder
{
  bindable.SetValue(PlaceholderElement.PlaceholderColorProperty, textColor);
  return bindable;
}

public static TBindable Placeholder<TBindable>(this TBindable bindable, string? text) where TBindable : BindableObject, IPlaceholder
{
  bindable.SetValue(PlaceholderElement.PlaceholderProperty, text);
  return bindable;
}

public static TBindable Placeholder<TBindable>(this TBindable bindable, string? text, Color? textColor) where TBindable : BindableObject, IPlaceholder
{
  return bindable.Placeholder(text).PlaceholderColor(textColor);
}
```

## Usage Syntax
[usage]: #usage-syntax

### C# Usage

```cs
Content = new VerticalStackLayout
{
  Children = 
  {
    new Entry().Placeholder("Phone Number", Colors.Grey),
    new Editor().Placeholder("Address, City, Zip", Colors.Grey)
  }
};
```

## Drawbacks
[drawbacks]: #drawbacks

## Alternatives
[alternatives]: #alternatives

The current alternative is to use property initialization:

```cs
Content = new VerticalStackLayout
{
  Children = 
  {
    new Entry { Placeholder = "Phone Number",  PlaceholderColor = Colors.Grey }
    new Editor { Placeholder = "Address, City, Zip",  PlaceholderColor = Colors.Grey }
  }
};
```

## Unresolved Questions
[unresolved]: #unresolved-questions

No known questions

**Comment by pictos** [comment]
I approve this feature ✅

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by brminnick** [comment]
I know I'm bias, but I approve too!

**Comment by brminnick** [comment]
Link to documentation: https://github.com/MicrosoftDocs/CommunityToolkit/pull/48
