### ISSUE TITLE
[Proposal] Add `IImage` Extension Methods

### ISSUE THREAD

**Issue by brminnick** [CommunityToolkit/Maui.Markup#45]
# Add `IImage` Extension Methods

* [x] Proposed
* [x] Prototype
* [x] Implementation
  * [x] iOS Support
  * [x] Android Support
  * [x] macOS Support
  * [x] Windows Support
* [x] Unit Tests
* [x] Sample
* [x] Documentation https://github.com/MicrosoftDocs/CommunityToolkit/pull/49

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/42

## Summary
[summary]: #summary

This Proposal adds the following fluent extension methods for `IImage`:

```cs
public static TBindable Source<TBindable>(this TBindable bindable, ImageSource imageSource) where TBindable : BindableObject, IImageSourcePart;

public static TBindable Aspect<TBindable>(this TBindable bindable, Aspect aspect) where TBindable : BindableObject, IImage;

public static TBindable IsOpaque<TBindable>(this TBindable bindable, bool isOpaque) where TBindable : BindableObject, IImage;
```

## Motivation
[motivation]: #motivation

Currently, the only way to assign values on an `Image` is to set the property directly, like so:

```cs
var image = new Image { Source = "dotnetbot", IsOpaque = true, Aspect = Aspect.AspectFill };
```

This Proposal allows us to instead assign these values using the fluent C# Markup syntax.

## Detailed Design
[design]: #detailed-design

```cs
public static TBindable Source<TBindable>(this TBindable bindable, ImageSource imageSource) where TBindable : BindableObject, IImageSourcePart
{
	bindable.SetValue(ImageElement.SourceProperty, imageSource);
	return bindable;
}

public static TBindable Aspect<TBindable>(this TBindable bindable, Aspect aspect) where TBindable : BindableObject, IImage
{
	bindable.SetValue(ImageElement.AspectProperty, aspect);
	return bindable;
}

public static TBindable IsOpaque<TBindable>(this TBindable bindable, bool isOpaque) where TBindable : BindableObject, IImage
{
	bindable.SetValue(ImageElement.IsOpaqueProperty, isOpaque);
	return bindable;
}
```

## Usage Syntax
[usage]: #usage-syntax

### C# Usage

```cs
Content = new Image().Source("dotnetbot").Aspect(Aspect.AspectFill).IsOpaque(true);
```

## Drawbacks
[drawbacks]: #drawbacks

No known drawbacks

## Alternatives
[alternatives]: #alternatives

The current alternative is to assign the properties upon initialization:
```cs
var image = new Image { Source = "dotnetbot", IsOpaque = true, Aspect = Aspect.AspectFill };
```

## Unresolved Questions
[unresolved]: #unresolved-questions

No unresolved questions

**Comment by pictos** [comment]
I approve this feature ✅

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by brminnick** [comment]
I also approve ✅
