### ISSUE TITLE
[Proposal] FlexLayout Basis<T> extension method overload + Doc and samples

### ISSUE THREAD

**Issue by danielftz** [CommunityToolkit/Maui.Markup#48]
# FlexLayout Basis<T> extension method overload

* [x] Proposed
* [x] Prototype
* [X] Implementation
  * [X] iOS Support
  * [X] Android Support
  * [X] macOS Support
  * [X] Windows Support
* [X] Unit Tests
* [x] Sample
* [x] Documentation https://github.com/MicrosoftDocs/CommunityToolkit/pull/53

## Link to Discussion

https://github.com/CommunityToolkit/Maui.Markup/discussions/34
## Summary
[summary]: #summary

This proposal adds a method overload to the ```Basis<T>``` extension method, so that ```FlexBasis``` can be set without the need for instantiating a ```FlexBasis``` struct. Also samples and docs for the existing FlexLayout methods will be added. 

## Motivation
[motivation]: #motivation

Allows for more options when declaring ```FlexBasis```. 

## Detailed Design
[design]: #detailed-design

```cs
public static TBindable Basis<TBindable>(this TBindable bindable, float length, bool isRelative = false) where TBindable : BindableObject
{
      return bindable.Basis(new FlexBasis(length, isRelative));
}
```

## Usage Syntax
[usage]: #usage-syntax

```cs
Content = new Label().Basis(25, true);
```
## Drawbacks
[drawbacks]: #drawbacks

None

## Alternatives
[alternatives]: #alternatives

None

## Unresolved Questions
[unresolved]: #unresolved-questions

None

**Comment by brminnick** [comment]
Thanks @danielftz! I approve this Proposal ✅ 

Once we get two more votes (ie a majority approval from the core team) we'll review + merge the Pull Request 🙌

**Comment by VladislavAntonyuk** [comment]
Approve

**Comment by pictos** [comment]
I approve this feature ✅
