### ISSUE TITLE
Support for AppThemeBindings

### ISSUE THREAD

**Issue by HobDev** [CommunityToolkit/Maui.Markup#76]
### Discussed in https://github.com/CommunityToolkit/Maui.Markup/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **HobDev** June 23, 2022</sup>
The docs have the `SetAppThemeColor()` and `SetAppTheme()`. This way I have to declare the colors on each UI element. There should be some better way to share style among the UI elements in C#. C# markup must support to declare the style once and use it throughout the app.

```
 static Color darkThemeTextColor = Color.FromArgb("#FFFFFF");
        static Color lightThemeTextColor = Color.FromArgb("#000000");

        static Style<Label> cSharpLabelStyle;
        public static Style<Label> CSharpLabelStyle => cSharpLabelStyle ?? (cSharpLabelStyle = new Style<Label>(
        (Label.TextColorProperty, new AppThemeBindingExtension { Dark = darkThemeTextColor, Light = lightThemeTextColor }),
        (Label.FontFamilyProperty, "OpenSansRegular"),
       (Label.FontSizeProperty, 14)
       ));
```
Finally use the style in UI :

`new Label{Text = "Hello World" , HorizontalOptions=LayoutOptions.Center, VerticalOptions=LayoutOptions.Center}.Style(AppStyles.CSharpLabelStyle),`</div>

In the attached sample the color of the XAML Label changes with the change of mode. But the C# Label does not change color until the app restarts.  Unable to check the change of device theme due to [this bug](https://github.com/dotnet/maui/issues/8236). 

[MauiApp1.zip](https://github.com/CommunityToolkit/Maui.Markup/files/8984614/MauiApp1.zip)

**Comment by brminnick** [comment]
@HobDev Please open a new Issue that adheres to the [New Feature Proposal Template](https://github.com/CommunityToolkit/Maui.Markup/issues/new?assignees=&labels=new%2C+proposal&template=open-a-new-feature-proposal.md&title=%5BProposal%5D+)

For more information see the instructions for **Submitting A New Feature** in the README: https://github.com/CommunityToolkit/Maui.Markup#submitting-a-new-feature
