### ISSUE TITLE
[♻Housekeeping] Improve our NuGet package quality 

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/Maui.Markup#92]
Today our NuGet package isn't great and after watching [this amazing talk from Claire](https://youtu.be/C_2BStepVKw) I saw that we can make our package even better!
Helping users to see our code from VS, and debug our code which will help us fix bugs (since the users can provide more complete information), we can prevent breaking changes, etc...  

I'll open one PR per item, to make it easy to review it and see if our CI will be happy.

[ ] Add Source-Link
[ ] Turn-on package validation

**Comment by brminnick** [comment]
![image](https://github.com/CommunityToolkit/Maui.Markup/assets/13558917/b97493bd-e6e6-414e-9eda-39c5b68ae6fe)

https://github.com/dotnet/sourcelink

**Comment by pictos** [comment]
@brminnick should we remove the package added by the #93?

**Comment by brminnick** [comment]
No worries! #93 was never merged ✅

**Comment by pictos** [comment]
Oh, I thought this way the MCT. We merged the package there

**Comment by brminnick** [comment]
No worries there too! Vlad removed it in the .NET 8 PR
